Hourly notification
poooi/plugin-secretary pull request #9
Opened 2016-10-10 12:42 UTC by KagamiChan

Add hourly notification function

基本可用了，没有登录情况下的报时可能会不对，不过，嘛……
P.S. 恢复默认语音的按钮长度改成 8 是因为日语语言情况下文字较长可能会超出按钮

请求日语支援

2016-10-10 12:46 UTC, yukixz commented
最好不要 hardcode 的依赖 poi 本体文件、以免 poi 更新的时候无法预料的插件损坏。可以考虑复制粘贴一份过来=。=

2016-10-10 12:47 UTC, KagamiChan commented
你是说的 scheduler 吗？那个应该没有改的计划吧 - -

2016-10-10 12:48 UTC, KagamiChan commented
嗯，我试试看能不能拿一份过来

2016-10-10 12:49 UTC, yukixz commented
改的时候是不会有人去注意插件会不会引用了的 =。=

2016-10-10 12:54 UTC, KagamiChan commented
已添加

2016-10-10 12:56 UTC, yukixz requested changes

2016-10-10 12:56 UTC, yukixz commented on index.cjsx
> +      hasHourlyVoice: _.find(getStore('const').$ships, (sh) -> return sh.api_id == ship_id)?.api_voicef > 1
可以直接用 `$ships[ship_id]` 访问的、`$ships` 的下标就是 `api_id` =。=

2016-10-10 12:56 UTC, yukixz commented on index.cjsx
> +    return unless config.get('plugin.secretary.enable', false)
印象中插件是否启用不是这个值

2016-10-10 12:56 UTC, yukixz commented on index.cjsx
> +        config.set("plugin.secretary.hourly_voice.#{hour}", audio)
可以在播放的时候再生成 url、免得往 config 里塞一堆 url。

2016-10-10 12:58 UTC, yukixz commented
可以考虑在 pluginDidUnload 的时候 destory scheduler 从而避免检查插件是否启用、还能避免插件「启用、禁用、启用」后可能导致多次播放的问题

2016-10-10 13:00 UTC, KagamiChan commented on index.cjsx
> +    return unless config.get('plugin.secretary.enable', false)
嗯……忘了这个已经改了 - -

2016-10-10 13:04 UTC, KagamiChan commented on index.cjsx
> +    return unless config.get('plugin.secretary.enable', false)
干脆不检测了吧，禁用的话就 unload 了，把 scheduler 给 destroy 就行

2016-10-10 13:06 UTC, yukixz commented on index.cjsx
> +    return unless config.get('plugin.secretary.enable', false)
是、destory 还可以节省一丁点资源（装作有一个亿

2016-10-10 13:15 UTC, KagamiChan commented
请教一下在这里 destroy 应该怎么做？ 
···
scheduler = null
delete scheduler
delete require.cache[require.resolve(./scheduler)]
···

2016-10-10 13:19 UTC, yukixz commented
改一下 scheduler、`scheduleNextTick` 加个 `if this.isStopped`。好像只能这样

2016-10-10 13:23 UTC, KagamiChan commented
scheduler._tasks =[]
……

2016-10-10 13:26 UTC, KagamiChan commented on index.cjsx
> +        config.set("plugin.secretary.hourly_voice.#{hour}", audio)
播放时候生成的话，就需要单独再做一遍 ship_id 的检查，还有获得提督名之类的……

2016-10-10 13:27 UTC, yukixz commented on index.cjsx
> +        config.set("plugin.secretary.hourly_voice.#{hour}", audio)
一小时一次不怕

2016-10-10 13:30 UTC, yukixz commented
[哭笑]

2016-10-10 13:54 UTC, KagamiChan commented
改成这样子不知道如何？

2016-10-10 14:41 UTC, yukixz commented
@KagamiChan 👍🏻

2016-10-10 14:41 UTC, yukixz approved these changes

2016-10-10 14:42 UTC, yukixz commented
明天测试一下、没 bug 就发新版本.

2016-10-10 14:42 UTC, merged

2016-10-10 16:04 UTC, dkwingsmt commented
@yukixz utils 文件夹里的东西都是 lts，兼容性会保障，可以直接 hardcode 引用。反对复制粘贴代码。

2016-10-10 16:06 UTC, KagamiChan commented
@dkwingsmt 目前没有从 scheduler 里面删除 task 的方法，为了让插件禁用或者卸载的时候停止定时任务，也有必要保留一个……

2016-10-10 16:15 UTC, dkwingsmt commented
@KagamiChan 你帮咱加一个呀

2016-10-10 16:17 UTC, KochiyaOcean reviewed
Japanese translation

2016-10-10 16:17 UTC, KochiyaOcean commented on i18n/ja-JP.json
> +  "No voice available": "時報ありません",
時報ボイスがありません

2016-10-10 16:17 UTC, KochiyaOcean commented on i18n/ja-JP.json
> +  "Play secretary's hourly voice when volume off": "ボリュームオフ時に秘書艦時報を再生する",
ボリュームがオンの時に秘書艦の時報ボイスを再生する

2016-10-10 16:17 UTC, KochiyaOcean commented on i18n/ja-JP.json
> +  "Hourly Voice": "時報",
時報ボイス

2016-10-10 16:18 UTC, KagamiChan commented
@dkwingsmt 那就加一个任务可选参数 tag，还有一个方法 cancelByTag() ？

2016-10-10 16:32 UTC, dkwingsmt commented
那你自己复制粘贴一个吧。反正代码行数也不多。

2016-10-10 17:19 UTC, KagamiChan commented
嗯，看 yuki 的想法，研究了一下，有了 lodash ，实现起来也不是很难，估计也不用保证任务的唯一性……

```
diff --git a/views/services/scheduler.es b/views/services/scheduler.es
index 9e35f95..d9d1e82 100644
--- a/views/services/scheduler.es
+++ b/views/services/scheduler.es
@@ -1,4 +1,4 @@
-import { sortBy, cloneDeep, partial } from 'lodash'
+import { sortBy, cloneDeep, partial, remove, toString } from 'lodash'
 
 const INTERVAL = 1000
 
@@ -59,6 +59,8 @@ class Scheduler {
       opts.time = Date.now()
     if (!('allowImmediate' in opts))
       opts.allowImmediate = true
+    if (!('tag' in opts))
+      opts.tag = toString(Date.now())
     return opts
   }
 
@@ -96,6 +98,11 @@ class Scheduler {
     this._pushTask(task)
     this._tryTasks()
   }
+
+  cancelbyTag(tag){
+    let tagString = toString(tag)
+    remove(this._tasks, task => task.opts.tag == tagString)
+  }
 }
 
 export default new Scheduler()
```

2016-10-10 17:23 UTC, dkwingsmt commented
你内部用的话你方便写就行。
如果我加在全局的话我会趋向于不自定义 tag，而是利用返回值。schedule 方法要么返回一个随机 tag 用于取消任务索引，要么返回一个数据结构用于取消任务索引，要么返回一个数据结构直接有一个 cancel 方法来取消自己。依赖外部 tag 的话任务唯一性很成问题，作为全局服务不得不考虑到这个问题。
不过还是那句话，你自己用的话方便就行。

2016-10-10 17:27 UTC, KagamiChan commented
OK

2016-10-19 12:02 UTC, KochiyaOcean commented on i18n/ja-JP.json
> +  "Play secretary's hourly voice when volume off": "ボリュームオフ時に秘書艦時報を再生する",
才发现这里写错了…… 应该是 オフ （面壁

2016-10-19 12:03 UTC, KochiyaOcean commented on index.cjsx
> +    notify __("It's %s now", "#{nowHourString}00"),
建议改成纯声音提示